Make edit default
waterloo-rocketry/minerva pull request #29
Opened 2021-01-27 23:34 UTC by wendi-yu

Makes the `meeting` command default to `edit` if no option is specified, instead of throwing an error.
Also changes the time zone detection to be automatic, instead of being hardcoded as Toronto.

2021-01-27 23:35 UTC, jacobdeery reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/29)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @chrissank and @wendi-yu)

___
*[src/commands/meeting.js, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/29#-MS5Bk2S010QaH9JeczP:-MS5Bk2S010QaH9JeczQ:bo9j6vg) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/16ebc8291cbcde63438585d6d7ecef8f48e069d8/src/commands/meeting.js#L5)):*
> ```JavaScript
>         return require("./meeting/reminder").send(originChannelID);
>     // the "edit" path is the default if no textParam is provided
>     } else {
> ```

hmm, this means that `/meeting remind` or anything other than `/meeting reminder` will open the edit dialogue. Is that what we want?


<!-- Sent from Reviewable.io -->

2021-01-27 23:38 UTC, wendi-yu reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/29)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @chrissank and @jacobdeery)

___
*[src/commands/meeting.js, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/29#-MS5Bk2S010QaH9JeczP:-MS5CJsG4Tb40y6MEOeo:b-xnzxd3) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/16ebc8291cbcde63438585d6d7ecef8f48e069d8/src/commands/meeting.js#L5)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

hmm, this means that `/meeting remind` or anything other than `/meeting reminder` will open the edit dialogue. Is that what we want?
</blockquote></details>

We could have it be `startsWith("remind")`, the main thing was that I wasn't sure if there was anything delineating the second part of the command from the beginning of the regular text


<!-- Sent from Reviewable.io -->

2021-01-27 23:39 UTC, jacobdeery reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/29)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @chrissank and @wendi-yu)

___
*[src/commands/meeting.js, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/29#-MS5Bk2S010QaH9JeczP:-MS5CdFs4X984ZpvK_oe:b-13knca) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/16ebc8291cbcde63438585d6d7ecef8f48e069d8/src/commands/meeting.js#L5)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

We could have it be `startsWith("remind")`, the main thing was that I wasn't sure if there was anything delineating the second part of the command from the beginning of the regular text
</blockquote></details>

sure, I'm more asking if we want `/meeting <anything>` to go to `edit` or if it should just be `/meeting` and `/meeting edit`


<!-- Sent from Reviewable.io -->

2021-01-27 23:42 UTC, wendi-yu reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/29)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @chrissank and @jacobdeery)

___
*[src/commands/meeting.js, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/29#-MS5Bk2S010QaH9JeczP:-MS5D0HkCq29fzHnLDsb:b4gwqof) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/16ebc8291cbcde63438585d6d7ecef8f48e069d8/src/commands/meeting.js#L5)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

sure, I'm more asking if we want `/meeting <anything>` to go to `edit` or if it should just be `/meeting` and `/meeting edit`
</blockquote></details>

ohh wait I thought there was text after the `/meeting` or the `meeting/edit`, like command line options or something. The wide net also made me a little uncomfortable lol, I think I agree that we should only limit it to the two


<!-- Sent from Reviewable.io -->

2021-01-28 01:29 UTC, chrissank requested changes
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/29)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[src/commands/meeting.js, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/29#-MS5Bk2S010QaH9JeczP:-MS5Zlby71fxEZkaMf_t:b-4hdvnn) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/16ebc8291cbcde63438585d6d7ecef8f48e069d8/src/commands/meeting.js#L5)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

ohh wait I thought there was text after the `/meeting` or the `meeting/edit`, like command line options or something. The wide net also made me a little uncomfortable lol, I think I agree that we should only limit it to the two
</blockquote></details>

I agree with jacob, `/meeting` and `/meeting edit` should act as `/meeting edit`, `/meeting reminder` stays the same, and then `/meeting <anything>` gives the help menu.
___
*[src/commands/meeting/edit.js, line 82 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva/29#-MS5ZwPY8P3rj_-lOpYe:-MS5ZwPY8P3rj_-lOpYf:b-sor926) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/2c0e6ed75e220468906ec4092c0130b64f80701f/src/commands/meeting/edit.js#L82)):*
> ```JavaScript
> 
>     meetingBlock.blocks[0].text.text =
>         "Editing meeting: *" + event.summary + "* occuring on *" + moment(event.start.dateTime).tz(moment.tz.guess()).format("MMMM Do, YYYY [at] h:mm A") + "*";
> ```

I'll check the functionality of this on the development Slack, but I think there's a possibility that if Slack's servers are hosted outside of the Eastern TZ we will run into issues with what time it displays. 

Check `__tests__/unit/initialize.test.js`, I used MockDate when I ran into a similar issue with GitHub actions. Maybe there's a solution in there? 


<!-- Sent from Reviewable.io -->

2021-01-28 05:55 UTC, wendi-yu reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/29)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chrissank and @jacobdeery)

___
*[src/commands/meeting.js, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/29#-MS5Bk2S010QaH9JeczP:-MS6Y8er39IPWEsbNj9_:bqwz9pf) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/16ebc8291cbcde63438585d6d7ecef8f48e069d8/src/commands/meeting.js#L5)):*
<details><summary><i>Previously, chrissank (Chris Sankey) wrote…</i></summary><blockquote>

I agree with jacob, `/meeting` and `/meeting edit` should act as `/meeting edit`, `/meeting reminder` stays the same, and then `/meeting <anything>` gives the help menu.
</blockquote></details>

Cool yeah, fixed this
___
*[src/commands/meeting/edit.js, line 82 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva/29#-MS5ZwPY8P3rj_-lOpYe:-MS6YI6Q9qq6sCWlV9fQ:b-xkbkwl) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/2c0e6ed75e220468906ec4092c0130b64f80701f/src/commands/meeting/edit.js#L82)):*
<details><summary><i>Previously, chrissank (Chris Sankey) wrote…</i></summary><blockquote>

I'll check the functionality of this on the development Slack, but I think there's a possibility that if Slack's servers are hosted outside of the Eastern TZ we will run into issues with what time it displays. 

Check `__tests__/unit/initialize.test.js`, I used MockDate when I ran into a similar issue with GitHub actions. Maybe there's a solution in there? 
</blockquote></details>

Yeah, I was looking at the documentation and it says it uses browser information to figure out what timezone it is, and then it should


<!-- Sent from Reviewable.io -->

2021-03-22 22:36 UTC, wendi-yu reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/29)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chrissank and @jacobdeery)

___
*[src/commands/meeting/edit.js, line 82 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva/29#-MS5ZwPY8P3rj_-lOpYe:-MWR42a27TH91GQjvAhF:bgdcpb7) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/2c0e6ed75e220468906ec4092c0130b64f80701f/src/commands/meeting/edit.js#L82)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Yeah, I was looking at the documentation and it says it uses browser information to figure out what timezone it is, and then it should
</blockquote></details>

Yeah I just reverted this and fixed the unit test instead to specify the timezone as America/Toronto, in hindsight it might be more consistent for Minerva to send the times in EST anyways


<!-- Sent from Reviewable.io -->

2021-03-30 00:33 UTC, jacobdeery approved these changes
I'm happy with this

2021-04-03 20:48 UTC, chrissank approved these changes
> Reviewed 1 of 1 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/29)* status: all files reviewed, 1 unresolved discussion (waiting on @jacobdeery)



<!-- Sent from Reviewable.io -->

2021-04-03 21:18 UTC, merged